version: 1.0.{build}
image: Visual Studio 2017
build_script:
- ps: >-
    dotnet build

    dotnet pack src\EdiWeave.Framework\EdiWeave.Framework.csproj
    
    dotnet pack src\EdiWeave.Core\EdiWeave.Core.csproj
artifacts:
- path: src\EdiWeave.Framework\bin\Debug\*.nupkg
- path: src\EdiWeave.Core\bin\Debug\*.nupkg