version: 1.0.{build}
image: Visual Studio 2017
build_script:
- ps: >-
    nuget restore EdiWeave.sln
    dotnet build

    dotnet pack Framework\Framework.csproj
artifacts:
- path: Framework\bin\Debug\*.nupkg